AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HLS画像取得エンドポイント用CloudFormationテンプレート

Parameters:
  CameraId:
    Type: String
    Default: camera001
    Description: カメラID（ECSタスク用）
  CollectorId:
    Type: String
    Description: コレクターID
  HlsRecRepositoryUri:
    Type: String
    Description: HlsRec ECRリポジトリURI（別テンプレートでデプロイ済）
  EcsTaskRoleArn:
    Type: String
    Description: ECSタスクロールのARN（別テンプレートでデプロイ済）
  EcsTaskExecutionRoleArn:
    Type: String
    Description: ECSタスク実行ロールのARN（別テンプレートでデプロイ済）
  CollectorSecurityGroupId:
    Type: String
    Description: コレクターセキュリティグループのID（別テンプレートでデプロイ済）
  CameraClusterName:
    Type: String
    Description: カメラECSクラスター名（別テンプレートでデプロイ済）
  PrivateSubnet1Id:
    Type: String
    Description: プライベートサブネット1のID（別テンプレートでデプロイ済）
  PrivateSubnet2Id:
    Type: String
    Description: プライベートサブネット2のID（別テンプレートでデプロイ済）
  BucketName:
    Type: String
    Description: S3バケット名（メインスタックから取得）
  TaskMemory:
    Type: Number
    Default: 512
    Description: タスクのメモリ（MB）。collector_modeに応じて動的に設定される（image=512, video/image_and_video=7168）
  TaskCpu:
    Type: Number
    Default: 256
    Description: タスクのCPU。collector_modeに応じて動的に設定される（image=256, video/image_and_video=1024）
  LogsKmsKeyArn:
    Type: String
    Description: CloudWatch Logs暗号化用KMS Key ARN

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.9
    Architectures:
      - x86_64
    Environment:
      Variables:
        PYTHONPATH: /var/task

Resources:
  # ECS タスク定義
  HlsRecTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Metadata:
      cdk_nag:
        rules_to_suppress:
          - id: AwsSolutions-ECS2
            reason: "環境変数にはセンシティブデータは含まれず、設定値(AWS_REGION, CAMERA_ID等)のみ"
    Properties:
      Family: !Sub "${CameraId}-${CollectorId}-task"
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: !Ref TaskCpu
      Memory: !Ref TaskMemory
      ExecutionRoleArn: !Ref EcsTaskExecutionRoleArn
      TaskRoleArn: !Ref EcsTaskRoleArn
      ContainerDefinitions:
        - Name: !Sub "${CameraId}-${CollectorId}-container"
          Image: !Ref HlsRecRepositoryUri
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref HlsRecLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: hlsrec
          Environment:
            - Name: AWS_REGION
              Value: !Ref AWS::Region
            - Name: CAMERA_ID
              Value: !Ref CameraId
            - Name: COLLECTOR_ID
              Value: !Ref CollectorId
            - Name: BUCKET_NAME
              Value: !Ref BucketName

  # ECS サービス
  HlsRecService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub "${CameraId}-${CollectorId}-service"
      Cluster: !Ref CameraClusterName
      TaskDefinition: !Ref HlsRecTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref CollectorSecurityGroupId
          Subnets:
            - !Ref PrivateSubnet1Id
            - !Ref PrivateSubnet2Id
      ServiceConnectConfiguration:
        Enabled: true
      Tags:
        - Key: Description
          Value: Service for HLS image download

  # CloudWatch ロググループ
  HlsRecLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${CameraId}-${CollectorId}"
      RetentionInDays: 14
      KmsKeyId: !Ref LogsKmsKeyArn

Outputs:
  HlsRecTaskDefinitionArn:
    Description: ARN of the HlsRec Task Definition
    Value: !Ref HlsRecTaskDefinition
  HlsRecServiceName:
    Description: Name of the HlsRec Service
    Value: !Ref HlsRecService
